Fix/3
OctoPrint/bundleviewer.octoprint.org pull request #7
Opened 2022-06-30 08:22 UTC by max246

Implemented a filter option to hide serial logs about temperature, it uses a toggle functionality to trigger on and off.

2022-09-07 14:25 UTC, foosel commented
FYI, seen the review request, it's on my TODO list, but I'm currently fully focused on 1.8.3.

2022-09-28 15:08 UTC, foosel commented
I'm a bit unsure about what this would accomplish in the context of the bundleviewer. Given that it is a debugging tool, even temperature lines are usually important, as their timing information can give infos on how the printed processes commands and how long it needs to process queries and such.

In the context of OctoPrint's terminal tab, yes, they can be unwelcome noise, but in the context of viewing `serial.log` from a system info bundle, I find them quite important for the full picture, just like every other single line. 

Can you elaborate?

2022-09-28 15:17 UTC, foosel commented
And it seems like I'm really behind things, I totally forgot that this was a feature request. Let me raise the question on that instead.

2022-10-01 09:39 UTC, max246 commented
> And it seems like I'm really behind things, I totally forgot that this was a feature request. Let me raise the question on that instead.

Yes it was :) I just picked a while ago form the backlog list.

2022-10-12 15:46 UTC, foosel requested changes
First of all thanks for your patience, also in me clarifying the intent behind the initial request again. Now, sadly, I'm really not happy with this way of implementing it 😕 There are some direct todos further below, but also these bigger points (ordered by priority):

- The Searchbar should really not care about showing a filter button based on log names, it should just get a boolean prop set if it should show that button and have a callback for toggling it.
- I also don't like how it fully removes the lines, without any hint that they were there. OctoPrint's terminal filters inject `[...]` where stuff was filtered out (but only once per multiple filtered lines) and also indicates number of visible vs. total lines. That makes it easier for someone looking at the terminal - and here the `serial.log` - to understand that filtering is happening, and to disable that again if that was a mistake. 
- We need more flexibility in the search options here. Right now the button does one single thing, filtering out `Recv: T...` lines. That's not on par with the functionality of terminal filters present in OctoPrint. I'd prefer to have some kind of menu here to select at least the same filter options (powered by a passed property).
- Yet another issue with how filtered lines are represented: We also have line numbers here, and that makes it even more tricky. They should reflect filtered lines, so "1, 2, 3, 8, 9, 10" if lines 4-7 were filtered.  Maybe it's possible to adjust the LogLines to do all of this?

2022-10-12 15:46 UTC, foosel commented on src/components/LogView.js
> +                        result.push(index);
Remove that whitespace please

2022-10-12 15:46 UTC, foosel commented on src/components/LogView.js
> +    //const lines = content.trim().split("\n").map((line) => (line.trimEnd() + "\n"));
Remove this please if it's no longer needed

2022-10-12 15:46 UTC, foosel commented on src/components/LogView.js
> +    }
```suggestion
    const onPerformFilter = (type) => {
        let filtered = false;
        if (type === "temperature") {
            filtered = line => line.match(reTemperature);
        }

        const result = content.trim().split("\n").map((line) => (line.trimEnd() + "\n")).filter(line => !filtered || !filtered(line));
        setLineCount(result.length);
        setLines(result);
    }
```

2022-10-12 15:46 UTC, foosel commented on src/components/LogView.js
> +
Remove that whitespace please

2022-10-12 15:46 UTC, foosel commented on src/components/LogView.js
> +
Some extra empty lines here, please remove.

2022-10-12 15:46 UTC, foosel commented on src/components/SearchBar.js
> +    }
Why the switch to a `{ return ... }` here? 🤔

And this breaks utilization of the outer `props.onPrev`, `props.onNext` and thus the search function.

2022-10-13 15:33 UTC, merged

2022-10-13 15:34 UTC, foosel commented
Decided to give this a whirl myself and implemented skipped line indicators (`[...]`), line number skipping, flexible filters, and also refactored things a bit.